[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "vague meadow palace solve shadow protect alpha annual fault silent forum card milk upgrade force diet naive flee subway vendor pretty throw subject songs"
